/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package home;

import account.login;
import javax.swing.JOptionPane;
import menu.Appointments;
import menu.CreateInvoiceFrame;
import menu.Doctor;
import menu.Employees;
import menu.InvoiceAdmin;

import menu.Medicines;
import menu.MedicinesCategory;
import menu.Patient;


/**
 *
 * @author PC
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        Appointments2 = new javax.swing.JButton();
        jdoctoc2 = new javax.swing.JButton();
        jemloyee2 = new javax.swing.JButton();
        invoice2 = new javax.swing.JButton();
        jmedicine2 = new javax.swing.JButton();
        jmedicine_ctgr2 = new javax.swing.JButton();
        jpatient2 = new javax.swing.JButton();
        jinvoive2 = new javax.swing.JButton();
        jlogout2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setFocusable(false);

        jPanel4.setBackground(new java.awt.Color(204, 255, 255));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.green, java.awt.Color.green, java.awt.Color.green, java.awt.Color.green));
        jPanel4.setEnabled(false);

        Appointments2.setBackground(new java.awt.Color(153, 204, 255));
        Appointments2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Appointments2.setText("Appointments");
        Appointments2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AppointmentsActionPerformed(evt);
            }
        });

        jdoctoc2.setBackground(new java.awt.Color(153, 204, 255));
        jdoctoc2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jdoctoc2.setText("Doctor");
        jdoctoc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdoctocActionPerformed(evt);
            }
        });

        jemloyee2.setBackground(new java.awt.Color(153, 204, 255));
        jemloyee2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jemloyee2.setText("Emloyees");
        jemloyee2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jemloyeeActionPerformed(evt);
            }
        });

        invoice2.setBackground(new java.awt.Color(153, 204, 255));
        invoice2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        invoice2.setText("Invoice");
        invoice2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invoiceActionPerformed(evt);
            }
        });

        jmedicine2.setBackground(new java.awt.Color(153, 204, 255));
        jmedicine2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jmedicine2.setText("Medicine");
        jmedicine2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmedicineActionPerformed(evt);
            }
        });

        jmedicine_ctgr2.setBackground(new java.awt.Color(153, 204, 255));
        jmedicine_ctgr2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jmedicine_ctgr2.setText("Medicines Category");
        jmedicine_ctgr2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmedicine_ctgrActionPerformed(evt);
            }
        });

        jpatient2.setBackground(new java.awt.Color(153, 204, 255));
        jpatient2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jpatient2.setText("Patient");
        jpatient2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpatientActionPerformed(evt);
            }
        });

        jinvoive2.setBackground(new java.awt.Color(153, 204, 255));
        jinvoive2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jinvoive2.setText("Create Invoice ");
        jinvoive2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jinvoiveActionPerformed(evt);
            }
        });

        jlogout2.setBackground(new java.awt.Color(153, 204, 255));
        jlogout2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlogout2.setText("Logout");
        jlogout2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlogoutActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ceo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(Appointments2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jemloyee2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jpatient2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jdoctoc2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(16, 16, 16))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jmedicine2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jinvoive2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jmedicine_ctgr2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                                .addComponent(invoice2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(16, 16, 16))))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jlogout2)
                .addContainerGap(151, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(162, 162, 162))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel3)
                .addGap(49, 49, 49)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jpatient2)
                    .addComponent(jdoctoc2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jemloyee2)
                    .addComponent(Appointments2))
                .addGap(44, 44, 44)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jmedicine_ctgr2)
                    .addComponent(invoice2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jmedicine2)
                    .addComponent(jinvoive2))
                .addGap(97, 97, 97)
                .addComponent(jlogout2)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlogoutActionPerformed
        int option = JOptionPane.showConfirmDialog(null, "Are you sure you want to log out?", "Confirm Logout", JOptionPane.YES_NO_OPTION);

        // Xử lý hành động của người dùng
        if (option == JOptionPane.YES_OPTION) {
            // Chuyển đến trang đăng nhập
            login loginFrame = new login();
            loginFrame.setVisible(true);
            loginFrame.pack();
            loginFrame.setLocationRelativeTo(null);
            this.dispose();
        } else {
            // Người dùng chọn "Không", không thực hiện hành động gì
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jlogoutActionPerformed

    private void jinvoiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jinvoiveActionPerformed
        CreateInvoiceFrame CreateInvoiceFrameJava = new CreateInvoiceFrame();
        CreateInvoiceFrameJava.setVisible(true);

        CreateInvoiceFrameJava.setLocationRelativeTo(null);

    }//GEN-LAST:event_jinvoiveActionPerformed

    private void jpatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpatientActionPerformed
        Patient PatientFrame = new Patient();
        PatientFrame.setVisible(true);
        PatientFrame.pack();
        PatientFrame.setLocationRelativeTo(null);

    }//GEN-LAST:event_jpatientActionPerformed

    private void jmedicine_ctgrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmedicine_ctgrActionPerformed
        MedicinesCategory MedicinesCategoryFrame = new MedicinesCategory();
        MedicinesCategoryFrame.setVisible(true);
        MedicinesCategoryFrame.pack();
        MedicinesCategoryFrame.setLocationRelativeTo(null);

    }//GEN-LAST:event_jmedicine_ctgrActionPerformed

    private void jmedicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmedicineActionPerformed
        Medicines MedicinesFrame = new Medicines();
        MedicinesFrame.setVisible(true);
        MedicinesFrame.pack();
        MedicinesFrame.setLocationRelativeTo(null);

    }//GEN-LAST:event_jmedicineActionPerformed

    private void invoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invoiceActionPerformed
        InvoiceAdmin InvoiceAdminFrame = new InvoiceAdmin();
        InvoiceAdminFrame.setVisible(true);
        InvoiceAdminFrame.pack();
        InvoiceAdminFrame.setLocationRelativeTo(null);

    }//GEN-LAST:event_invoiceActionPerformed

    private void jemloyeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jemloyeeActionPerformed
        Employees EmployeesFrame = new Employees();
        EmployeesFrame.setVisible(true);
        EmployeesFrame.pack();
        EmployeesFrame.setLocationRelativeTo(null);

    }//GEN-LAST:event_jemloyeeActionPerformed

    private void jdoctocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdoctocActionPerformed
        Doctor DoctorFrame = new Doctor();
        DoctorFrame.setVisible(true);
        DoctorFrame.pack();
        DoctorFrame.setLocationRelativeTo(null);

    }//GEN-LAST:event_jdoctocActionPerformed

    private void AppointmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AppointmentsActionPerformed
        Appointments AppointmentsFrame = new Appointments();
        AppointmentsFrame.setVisible(true);
        AppointmentsFrame.pack();
        AppointmentsFrame.setLocationRelativeTo(null);

    }//GEN-LAST:event_AppointmentsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
           public void run() {
            login loginFrame = new login();
            loginFrame.setVisible(true);
            loginFrame.setLocationRelativeTo(null); // Center the frame on the screen
        }
    });


    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Appointments2;
    private javax.swing.JButton invoice2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton jdoctoc2;
    private javax.swing.JButton jemloyee2;
    private javax.swing.JButton jinvoive2;
    private javax.swing.JButton jlogout2;
    private javax.swing.JButton jmedicine2;
    private javax.swing.JButton jmedicine_ctgr2;
    private javax.swing.JButton jpatient2;
    // End of variables declaration//GEN-END:variables
}
